version: '2'
services:
    depillagos-app:
        image: depillagos
        external_links:
            - depillagos-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=depillagos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    depillagos-mongodb:
        extends:
            file: mongodb.yml
            service: depillagos-mongodb
