version: '2'
services:
    depillagos-mongodb:
        container_name: depillagos-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/depillagos/mongodb/:/data/db/
